services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'

    # makes controllers autowired with constructor arguments
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
